# Generated by Django 5.2.10 on 2026-03-27 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("icon", models.CharField(max_length=50)),
                ("color", models.CharField(max_length=50)),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Career",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("salary", models.CharField(max_length=50)),
                ("demand_level", models.CharField(max_length=50)),
                ("match_percentage", models.IntegerField(default=0)),
                ("slug", models.SlugField(unique=True)),
                ("skills", models.JSONField(default=list)),
                ("is_featured", models.BooleanField(default=False)),
                ("recommended", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="careers",
                        to="api.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoadmapStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phase", models.CharField(max_length=50)),
                ("label", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("order", models.IntegerField(default=0)),
                ("icon", models.CharField(max_length=50)),
                ("timeline", models.CharField(max_length=50)),
                (
                    "career",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roadmap_steps",
                        to="api.career",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
