# Generated by Django 6.0.1 on 2026-03-27 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, default='Aspiring Professional', max_length=200)),
                ('location', models.CharField(blank=True, default='India', max_length=100)),
                ('university', models.CharField(blank=True, default='Not specified', max_length=200)),
                ('about', models.TextField(blank=True, default='I am a passionate professional looking to explore new career opportunities and grow my skill set.')),
                ('skills', models.JSONField(blank=True, default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
